### ISSUE TITLE
Trouble compiling

### ISSUE THREAD

**Issue by posix4e** [thesam/rOSt#1]
Howdy, perhaps rust source tree has gone stale again
posix4e@posi:~/projects/rOSt$ make
nasm -o loader.bin -f bin loader.asm
rustc -O --target i686-unknown-linux-gnu -o libcore.rlib -C relocation-model=static -C no-stack-check -Ctarget-cpu=generic libcore/lib.rs
rustc -L /home/posix4e/rust_i386/lib/rustlib/i686-unknown-linux-gnu/lib/ -O --target i686-unknown-linux-gnu --crate-type lib --emit obj -o main.o -C relocation-model=static -Ctarget-cpu=generic main.rs
console.rs:79:16: 79:36 warning: unnecessary parentheses around `if` condition, #[warn(unused_parens)] on by default
console.rs:79             if (current_row < 24) {
                             ^~~~~~~~~~~~~~~~~~~~
main.rs:73:20: 73:24 warning: unused variable: `size`, #[warn(unused_variables)] on by default
main.rs:73 unsafe fn allocate(size: usize, _align: usize) -> _mut u8 {
                              ^~~~
main.rs:79:22: 79:25 warning: unused variable: `ptr`, #[warn(unused_variables)] on by default
main.rs:79 unsafe fn deallocate(ptr: *mut u8, _size: usize, _align: usize) {
                                ^~~
nasm -f elf32 -o lib.o lib.asm
ld -m elf_i386 -o main.bin -T linker.ld
main.o: In function `main':
main.0.rs:(.text.main+0xba7): undefined reference to`panicking::panic_bounds_check::h862553bfafe51ec3YDC'
Makefile:29: recipe for target 'main.bin' failed
make: *_\* [main.bin] Error 1
posix4e@posi:~/projects/rOSt$

**Comment by thesam** [comment]
Thanks for reporting this!
